FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /lms-service ./cmd/lms-service

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /lms-service /lms-service
EXPOSE 8002
CMD ["/lms-service"]
